// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _007_TaskFilm;

#nullable disable

namespace _007_TaskFilm.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20260304171337_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ActorFilm", b =>
                {
                    b.Property<int>("ActorsId")
                        .HasColumnType("int");

                    b.Property<int>("FilmsId")
                        .HasColumnType("int");

                    b.HasKey("ActorsId", "FilmsId");

                    b.HasIndex("FilmsId");

                    b.ToTable("ActorFilm");

                    b.HasData(
                        new
                        {
                            ActorsId = 1,
                            FilmsId = 1
                        },
                        new
                        {
                            ActorsId = 2,
                            FilmsId = 2
                        },
                        new
                        {
                            ActorsId = 3,
                            FilmsId = 3
                        },
                        new
                        {
                            ActorsId = 4,
                            FilmsId = 4
                        },
                        new
                        {
                            ActorsId = 5,
                            FilmsId = 5
                        },
                        new
                        {
                            ActorsId = 6,
                            FilmsId = 6
                        },
                        new
                        {
                            ActorsId = 1,
                            FilmsId = 4
                        },
                        new
                        {
                            ActorsId = 2,
                            FilmsId = 1
                        });
                });

            modelBuilder.Entity("_007_TaskFilm.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Keanu Reeves"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sam Neill"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Matthew McConaughey"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Russell Crowe"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Brendan Fraser"
                        });
                });

            modelBuilder.Entity("_007_TaskFilm.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MovieStudioId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MovieStudioId");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieStudioId = 1,
                            Name = "Inception",
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            MovieStudioId = 1,
                            Name = "The Matrix",
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            MovieStudioId = 2,
                            Name = "Jurassic Park",
                            ReleaseDate = new DateTime(1993, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            MovieStudioId = 1,
                            Name = "Interstellar",
                            ReleaseDate = new DateTime(2014, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            MovieStudioId = 3,
                            Name = "Gladiator",
                            ReleaseDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            MovieStudioId = 2,
                            Name = "The Mummy",
                            ReleaseDate = new DateTime(1999, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("_007_TaskFilm.MovieStudio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MovieStudios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Warner Bros"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Universal Pictures"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Paramount Pictures"
                        });
                });

            modelBuilder.Entity("ActorFilm", b =>
                {
                    b.HasOne("_007_TaskFilm.Actor", null)
                        .WithMany()
                        .HasForeignKey("ActorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_007_TaskFilm.Film", null)
                        .WithMany()
                        .HasForeignKey("FilmsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_007_TaskFilm.Film", b =>
                {
                    b.HasOne("_007_TaskFilm.MovieStudio", "MovieStudio")
                        .WithMany("Films")
                        .HasForeignKey("MovieStudioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieStudio");
                });

            modelBuilder.Entity("_007_TaskFilm.MovieStudio", b =>
                {
                    b.Navigation("Films");
                });
#pragma warning restore 612, 618
        }
    }
}
